baseURL = 'https://mysterycultist.com/'
languageCode = 'en-uk'
title = 'The Mystery Cultist'

[params]
    name = 'MysteryCultist'
    dateFormat = "2 January, 2006"

[taxonomies]
    tag = "tags"

[deployment]
    confirm = false
    dryRun = false
    force = false
    invalidateCDN = true
    maxDeletes = 256
    target = ''
    workers = 10

[markup.goldmark.renderer]
    hardWraps = true