baseURL = 'https://mysterycultist.org/'
languageCode = 'en-uk'
title = 'The Mystery Cultist'

[params]
    name = 'MysteryCultist'

[deployment]
    confirm = false
    dryRun = false
    force = false
    invalidateCDN = true
    maxDeletes = 256
    target = ''
    workers = 10